week:
    pattern:  /week/{year}/{week}
    defaults:
        _controller: MayflowerWochenplanerBundle:Week:index
        year: null
        week: null

MayflowerWochenplanerBundle_person:
    resource: "@MayflowerWochenplanerBundle/Resources/config/routing/person.yml"
    prefix:   /person
