task:
    pattern:  '/task'
    defaults: { _controller: "MayflowerTPPBundle:Task:index" }
    requirements: { _method: get }

task_create:
    pattern:  '/task'
    defaults: { _controller: "MayflowerTPPBundle:Task:create" }
    requirements: { _method: post }

task_update:
    pattern:  '/task/{id}'
    defaults: { _controller: "MayflowerTPPBundle:Task:update" }
    requirements: { _method: put }

task_delete:
    pattern:  '/task/{id}'
    defaults: { _controller: "MayflowerTPPBundle:Task:delete" }
    requirements: { _method: delete }

resource:
    pattern:  '/resource'
    defaults: { _controller: "MayflowerTPPBundle:Resource:index" }
    requirements: { _method: get }

resource_create:
    pattern:  '/resource'
    defaults: { _controller: "MayflowerTPPBundle:Resource:create" }
    requirements: { _method: post }

resource_update:
    pattern:  '/resource/{id}'
    defaults: { _controller: "MayflowerTPPBundle:Resource:update" }
    requirements: { _method: put }

resource_delete:
    pattern:  '/resource/{id}'
    defaults: { _controller: "MayflowerTPPBundle:Resource:delete" }
    requirements: { _method: delete }

project:
    pattern:  '/project'
    defaults: { _controller: "MayflowerTPPBundle:Project:index" }
    requirements: { _method: get }

project_create:
    pattern:  '/project'
    defaults: { _controller: "MayflowerTPPBundle:Project:create" }
    requirements: { _method: post }

project_update:
    pattern:  '/project/{id}'
    defaults: { _controller: "MayflowerTPPBundle:Project:update" }
    requirements: { _method: put }

project_delete:
    pattern:  '/project/{id}'
    defaults: { _controller: "MayflowerTPPBundle:Project:delete" }
    requirements: { _method: delete }
