week:
    pattern:  "/week/{week}/{year}"
    defaults:
        _controller: MayflowerTPPBundle:Week:index
        year: null
        week: null

MayflowerTPPBundle_resource:
    resource: "@MayflowerTPPBundle/Resources/config/routing/resource.yml"
    prefix:   /resource

MayflowerTPPBundle_category:
    resource: "@MayflowerTPPBundle/Resources/config/routing/category.yml"
    prefix:   /category
