parameters:
#    mayflower_tpp.example.class: Mayflower\TPPBundle\Example

services:
#    mayflower_tpp.example:
#        class: %mayflower_tpp.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
